version: '3.8'

services:
  app:
    build: .
    env_file: ./environment/.env
    volumes:
      - ./app:/app
    networks:
      - sizer-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    ports:
      - "80:80"
    networks:
      - sizer-network

networks:
  sizer-network:
    driver: bridge
